baseURL = "https://retty3d.github.io/"
languageCode = "ja-jp"
title = "れてぃのーと"
theme = "hugo-theme-techdoc"
publishDir = "docs"
canonifyurls = true


[params]
    menu_style = "slide-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar
