baseURL = "https://retty3d.github.io/"
languageCode = "ja-jp"
title = "れてぃのーと"
theme = "hugo-theme-techdoc"
publishDir = "docs"
canonifyurls = true
enableGitInfo = true

[params]
    AuthorName = "retty3d"
    GitHubUser = "retty3d"
    menu_style = "slide-menu"

[frontmatter]
    date = ['date', 'publishDate', 'lastmod']
    expiryDate = ['expiryDate']
    lastmod = [':git', 'lastmod', 'date', 'publishDate']
    publishDate = ['publishDate', 'date']
