title = "れてぃのーと"
baseURL = "https://retty3d.github.io/"
languageCode = "ja-jp"
theme = "hugo-book"
publishDir = "docs"

canonifyurls = true
enableGitInfo = true

[params]
    BookTheme      = "light"
    BookLogo       = "favicon/favicon.ico"
    BookSection    = "docs"
    BookToC        = false
    BookRepo       = "https://github.com/retty3d/retty3d.github.io"
    BookCommitPath = "commit"
    BookSearch     = true
    BookComments   = true

[frontmatter]
    date = ['date', 'publishDate', 'lastmod']
    expiryDate = ['expiryDate']
    lastmod = [':git', 'lastmod', 'date', 'publishDate']
    publishDate = ['publishDate', 'date']
